### ISSUE TITLE
Wiping does not seem to work

### ISSUE THREAD

**Issue by jlumbroso** [josephlou5/roseingrave#20]
I created this definition file:

```json
[
  {
    "name": "J\u00e9r\u00e9mie Lumbroso",
    "email": "lumbroso@princeton.edu",
    "pieces": ["K.533"]
  }
]
```
and called Roseingrave, then added "K.2" as a piece, and called it again (`create_sheet`) with the `-r` mode. It threw an exception, even though the wiping mode should expect to get existing definitions.

I then used the "extend" option which was the one I wanted any way 😁

```
(base) argos-cary (main*) » pipenv run roseingrave create_sheet -n -vd input/volunteer_definitions_test.json
2023-02-23 20:18:58.371 | INFO     | roseingrave._read_write:_settings:172 - Reading settings file
2023-02-23 20:18:58.372 | INFO     | roseingrave._sheets:gspread_auth:67 - Setting up gspread authentication
2023-02-23 20:19:07.963 | INFO     | roseingrave._input_files:read_template:55 - Reading template definitions file
2023-02-23 20:19:07.968 | WARNING  | roseingrave._input_files:read_template:100 - unknown key "metaDataFields"."endSignsX"
2023-02-23 20:19:07.968 | INFO     | roseingrave._input_files:_piece_definitions:200 - Reading piece definitions file
2023-02-23 20:19:07.970 | INFO     | roseingrave._input_files:_volunteer_definitions:344 - Reading volunteer definitions file
2023-02-23 20:19:07.971 | INFO     | roseingrave._output_files:read_spreadsheets_index:67 - Reading spreadsheets index file
2023-02-23 20:19:07.971 | INFO     | roseingrave.create_sheet:create_spreadsheets:108 - Creating new spreadsheets
2023-02-23 20:19:13.557 | INFO     | roseingrave.create_sheet:populate_spreadsheets:170 - Populating spreadsheets with pieces
2023-02-23 20:19:13.558 | DEBUG    | roseingrave.create_sheet:populate_spreadsheets:176 - Working on volunteer "lumbroso@princeton.edu"
2023-02-23 20:19:13.734 | DEBUG    | roseingrave.create_sheet:populate_spreadsheets:235 - Creating sheet for piece "K.533"
2023-02-23 20:19:15.213 | INFO     | roseingrave._read_write:_write:112 - Writing created spreadsheet links to "output/spreadsheets.json"
2023-02-23 20:19:15.221 | INFO     | roseingrave.create_sheet:create_sheet:456 - Done


(base) argos-cary (main*) » pipenv run roseingrave create_sheet -r -vd input/volunteer_definitions_test.json
2023-02-23 20:23:48.980 | INFO     | roseingrave._read_write:_settings:172 - Reading settings file
2023-02-23 20:23:48.981 | INFO     | roseingrave._sheets:gspread_auth:67 - Setting up gspread authentication
2023-02-23 20:23:56.673 | INFO     | roseingrave._input_files:read_template:55 - Reading template definitions file
2023-02-23 20:23:56.679 | WARNING  | roseingrave._input_files:read_template:100 - unknown key "metaDataFields"."endSignsX"
2023-02-23 20:23:56.679 | INFO     | roseingrave._input_files:_piece_definitions:200 - Reading piece definitions file
2023-02-23 20:23:56.682 | INFO     | roseingrave._input_files:_volunteer_definitions:344 - Reading volunteer definitions file
2023-02-23 20:23:56.682 | INFO     | roseingrave._output_files:read_spreadsheets_index:67 - Reading spreadsheets index file
2023-02-23 20:23:56.683 | INFO     | roseingrave.create_sheet:populate_spreadsheets:170 - Populating spreadsheets with pieces
2023-02-23 20:23:56.683 | DEBUG    | roseingrave.create_sheet:populate_spreadsheets:176 - Working on volunteer "lumbroso@princeton.edu"
2023-02-23 20:23:57.109 | DEBUG    | roseingrave.create_sheet:populate_spreadsheets:235 - Creating sheet for piece "K.533"
Traceback (most recent call last):
  File "/Users/jlumbroso/.local/share/virtualenvs/argos-cary-tYZdvy1o/bin/roseingrave", line 8, in <module>
    sys.exit(cli())
  File "/Users/jlumbroso/.local/share/virtualenvs/argos-cary-tYZdvy1o/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jlumbroso/.local/share/virtualenvs/argos-cary-tYZdvy1o/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/jlumbroso/.local/share/virtualenvs/argos-cary-tYZdvy1o/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jlumbroso/.local/share/virtualenvs/argos-cary-tYZdvy1o/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jlumbroso/.local/share/virtualenvs/argos-cary-tYZdvy1o/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jlumbroso/.local/share/virtualenvs/argos-cary-tYZdvy1o/lib/python3.9/site-packages/roseingrave/create_sheet.py", line 447, in create_sheet
    success = populate_spreadsheets(gc, volunteer_spreadsheets, pieces, strict)
  File "/Users/jlumbroso/.local/share/virtualenvs/argos-cary-tYZdvy1o/lib/python3.9/site-packages/roseingrave/create_sheet.py", line 236, in populate_spreadsheets
    sheet = pieces[piece_name].create_sheet(spreadsheet)
  File "/Users/jlumbroso/.local/share/virtualenvs/argos-cary-tYZdvy1o/lib/python3.9/site-packages/roseingrave/_piece.py", line 373, in create_sheet
    sheet = spreadsheet.add_worksheet(self._name, 1, 1)
  File "/Users/jlumbroso/.local/share/virtualenvs/argos-cary-tYZdvy1o/lib/python3.9/site-packages/gspread/spreadsheet.py", line 377, in add_worksheet
    data = self.batch_update(body)
  File "/Users/jlumbroso/.local/share/virtualenvs/argos-cary-tYZdvy1o/lib/python3.9/site-packages/gspread/spreadsheet.py", line 131, in batch_update
    r = self.client.request(
  File "/Users/jlumbroso/.local/share/virtualenvs/argos-cary-tYZdvy1o/lib/python3.9/site-packages/gspread/client.py", line 589, in request
    raise err
  File "/Users/jlumbroso/.local/share/virtualenvs/argos-cary-tYZdvy1o/lib/python3.9/site-packages/gspread/client.py", line 562, in request
    return super().request(*args, **kwargs)
  File "/Users/jlumbroso/.local/share/virtualenvs/argos-cary-tYZdvy1o/lib/python3.9/site-packages/gspread/client.py", line 92, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 400, 'message': 'Invalid requests[0].addSheet: A sheet with the name "K.533" already exists. Please enter another name.', 'status': 'INVALID_ARGUMENT'}


(base) argos-cary (main*) » pipenv run roseingrave create_sheet --help
Usage: roseingrave create_sheet [OPTIONS] [EMAILS]...

  Create volunteer spreadsheets.

Options:
  -e, --extend   Extend existing sheets with missing pieces. Cannot be set
                 when `--replace` or `--new` is set.
  -r, --replace  Wipe and replace existing volunteer spreadsheets. Cannot be
                 set when `--extend` is set. Has no effect when `--new` is
                 set.
  -n, --new      Create new spreadsheets for all volunteers. Cannot be set
                 when `--extend` is set.
  -td TEXT       A filepath to replace the template definitions file.
  -pd TEXT       A filepath to replace the piece definitions file.
  -vd TEXT       A filepath to replace the volunteer definitions file.
  -si TEXT       A filepath to replace the spreadsheets index file.
  --strict       Fail on warnings instead of only displaying them.
  --help         Show this message and exit.
(base) argos-cary (main*) » pipenv run roseingrave create_sheet -e -vd input/volunteer_definitions_test.json
2023-02-23 20:25:04.396 | INFO     | roseingrave._read_write:_settings:172 - Reading settings file
2023-02-23 20:25:04.397 | INFO     | roseingrave._sheets:gspread_auth:67 - Setting up gspread authentication
2023-02-23 20:25:06.642 | INFO     | roseingrave._input_files:read_template:55 - Reading template definitions file
2023-02-23 20:25:06.648 | WARNING  | roseingrave._input_files:read_template:100 - unknown key "metaDataFields"."endSignsX"
2023-02-23 20:25:06.648 | INFO     | roseingrave._input_files:_piece_definitions:200 - Reading piece definitions file
2023-02-23 20:25:06.652 | INFO     | roseingrave._input_files:_volunteer_definitions:344 - Reading volunteer definitions file
2023-02-23 20:25:06.653 | INFO     | roseingrave._output_files:read_spreadsheets_index:67 - Reading spreadsheets index file
2023-02-23 20:25:06.653 | INFO     | roseingrave.create_sheet:populate_spreadsheets:170 - Populating spreadsheets with pieces
2023-02-23 20:25:06.653 | DEBUG    | roseingrave.create_sheet:populate_spreadsheets:176 - Working on volunteer "lumbroso@princeton.edu"
2023-02-23 20:25:07.011 | DEBUG    | roseingrave.create_sheet:populate_spreadsheets:230 - Skipping piece "K.533": already exists in sheet
2023-02-23 20:25:07.011 | DEBUG    | roseingrave.create_sheet:populate_spreadsheets:235 - Creating sheet for piece "K.2"
2023-02-23 20:25:08.413 | INFO     | roseingrave.create_sheet:create_sheet:456 - Done
```

**Comment by josephlou5** [comment]
Sorry about that, this was due to a slight bug about forgetting to rename a temp sheet so that it wouldn't have a name conflict.

**Comment by jlumbroso** [comment]
Excellent @josephlou5, thanks for detecting and fixing so quickly! 🥳
