### ISSUE TITLE
Add some failure tolerance to quota errors — exponential back-off?

### ISSUE THREAD

**Issue by jlumbroso** [josephlou5/roseingrave#9]
While generating a big example sheet for myself, I ran into the following exception:
```
(argos-pilot) (base) argos-pilot (main) »  roseingrave create_sheet --replace                                                                                   ~/Programming/argos-pilot  
2022-06-29 23:48:47.243 | INFO     | roseingrave._read_write:_settings:166 - Reading settings file
2022-06-29 23:48:47.244 | INFO     | roseingrave._sheets:gspread_auth:55 - Setting up gspread authentication
2022-06-29 23:48:49.576 | INFO     | roseingrave._input_files:read_template:58 - Reading template definitions file
2022-06-29 23:48:49.577 | INFO     | roseingrave._input_files:_piece_definitions:188 - Reading piece definitions file
2022-06-29 23:48:49.579 | INFO     | roseingrave._input_files:_volunteer_definitions:340 - Reading volunteer definitions file
2022-06-29 23:48:49.579 | INFO     | roseingrave._output_files:read_spreadsheets_index:61 - Reading spreadsheets index file
2022-06-29 23:48:49.579 | INFO     | roseingrave.create_sheet:populate_spreadsheets:120 - Populating spreadsheets with pieces
2022-06-29 23:48:49.579 | DEBUG    | roseingrave.create_sheet:populate_spreadsheets:126 - Working on volunteer "lumbroso@princeton.edu"
2022-06-29 23:48:50.977 | DEBUG    | roseingrave.create_sheet:populate_spreadsheets:153 - Creating sheet for piece "K.16"
2022-06-29 23:48:53.057 | DEBUG    | roseingrave.create_sheet:populate_spreadsheets:153 - Creating sheet for piece "K.17"
2022-06-29 23:48:54.302 | DEBUG    | roseingrave.create_sheet:populate_spreadsheets:153 - Creating sheet for piece "K.19"
2022-06-29 23:48:55.603 | DEBUG    | roseingrave.create_sheet:populate_spreadsheets:153 - Creating sheet for piece "K.23"
2022-06-29 23:48:56.789 | DEBUG    | roseingrave.create_sheet:populate_spreadsheets:153 - Creating sheet for piece "K.25"
2022-06-29 23:48:58.031 | DEBUG    | roseingrave.create_sheet:populate_spreadsheets:153 - Creating sheet for piece "K.27"
2022-06-29 23:48:59.111 | DEBUG    | roseingrave.create_sheet:populate_spreadsheets:153 - Creating sheet for piece "K.48"
2022-06-29 23:49:00.041 | DEBUG    | roseingrave.create_sheet:populate_spreadsheets:153 - Creating sheet for piece "K.102"
2022-06-29 23:49:01.217 | DEBUG    | roseingrave.create_sheet:populate_spreadsheets:153 - Creating sheet for piece "K.109"
2022-06-29 23:49:02.088 | DEBUG    | roseingrave.create_sheet:populate_spreadsheets:153 - Creating sheet for piece "K.110"
2022-06-29 23:49:02.997 | DEBUG    | roseingrave.create_sheet:populate_spreadsheets:153 - Creating sheet for piece "K.139"
2022-06-29 23:49:04.081 | DEBUG    | roseingrave.create_sheet:populate_spreadsheets:153 - Creating sheet for piece "K.190"
2022-06-29 23:49:05.156 | DEBUG    | roseingrave.create_sheet:populate_spreadsheets:153 - Creating sheet for piece "K.211"
2022-06-29 23:49:05.987 | DEBUG    | roseingrave.create_sheet:populate_spreadsheets:153 - Creating sheet for piece "K.518"
2022-06-29 23:49:06.809 | DEBUG    | roseingrave.create_sheet:populate_spreadsheets:153 - Creating sheet for piece "K.519"
2022-06-29 23:49:07.768 | DEBUG    | roseingrave.create_sheet:populate_spreadsheets:153 - Creating sheet for piece "K.520"
2022-06-29 23:49:08.617 | DEBUG    | roseingrave.create_sheet:populate_spreadsheets:153 - Creating sheet for piece "K.521"
2022-06-29 23:49:09.562 | DEBUG    | roseingrave.create_sheet:populate_spreadsheets:153 - Creating sheet for piece "K.522"
2022-06-29 23:49:10.584 | DEBUG    | roseingrave.create_sheet:populate_spreadsheets:153 - Creating sheet for piece "K.523"
Traceback (most recent call last):
  File "/Users/jlumbroso/.local/share/virtualenvs/argos-pilot-XZjiRVec/bin/roseingrave", line 8, in <module>
    sys.exit(cli())
  File "/Users/jlumbroso/.local/share/virtualenvs/argos-pilot-XZjiRVec/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jlumbroso/.local/share/virtualenvs/argos-pilot-XZjiRVec/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/jlumbroso/.local/share/virtualenvs/argos-pilot-XZjiRVec/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jlumbroso/.local/share/virtualenvs/argos-pilot-XZjiRVec/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jlumbroso/.local/share/virtualenvs/argos-pilot-XZjiRVec/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jlumbroso/.local/share/virtualenvs/argos-pilot-XZjiRVec/lib/python3.9/site-packages/roseingrave/create_sheet.py", line 299, in create_sheet
    success = populate_spreadsheets(
  File "/Users/jlumbroso/.local/share/virtualenvs/argos-pilot-XZjiRVec/lib/python3.9/site-packages/roseingrave/create_sheet.py", line 156, in populate_spreadsheets
    sheet = pieces[piece_name].create_sheet(spreadsheet)
  File "/Users/jlumbroso/.local/share/virtualenvs/argos-pilot-XZjiRVec/lib/python3.9/site-packages/roseingrave/_piece.py", line 417, in create_sheet
    sheet.update(values, raw=False)
  File "/Users/jlumbroso/.local/share/virtualenvs/argos-pilot-XZjiRVec/lib/python3.9/site-packages/gspread/utils.py", line 634, in wrapper
    return f(*args, **kwargs)
  File "/Users/jlumbroso/.local/share/virtualenvs/argos-pilot-XZjiRVec/lib/python3.9/site-packages/gspread/worksheet.py", line 840, in update
    response = self.spreadsheet.values_update(
  File "/Users/jlumbroso/.local/share/virtualenvs/argos-pilot-XZjiRVec/lib/python3.9/site-packages/gspread/spreadsheet.py", line 225, in values_update
    r = self.client.request("put", url, params=params, json=body)
  File "/Users/jlumbroso/.local/share/virtualenvs/argos-pilot-XZjiRVec/lib/python3.9/site-packages/gspread/client.py", line 86, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 429, 'message': "Quota exceeded for quota metric 'Write requests' and limit 'Write requests per minute per user' of service 'sheets.googleapis.com' for consumer 'project_number:576121055363'.", 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'RATE_LIMIT_EXCEEDED', 'domain': 'googleapis.com', 'metadata': {'service': 'sheets.googleapis.com', 'quota_limit_value': '60', 'consumer': 'projects/576121055363', 'quota_limit': 'WriteRequestsPerMinutePerUser', 'quota_location': 'global', 'quota_metric': 'sheets.googleapis.com/write_requests'}}, {'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Request a higher quota limit.', 'url': 'https://cloud.google.com/docs/quota#requesting_higher_quota'}]}]}
```

Here is the error:
```
gspread.exceptions.APIError: {'code': 429, 'message':
"Quota exceeded for quota metric 'Write requests' and limit 'Write requests
per minute per user' of service 'sheets.googleapis.com' for consumer
'project_number:576121055363'.", 'status': 'RESOURCE_EXHAUSTED',
'details': [{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason':
'RATE_LIMIT_EXCEEDED', 'domain': 'googleapis.com', 'metadata': {'service':
'sheets.googleapis.com', 'quota_limit_value': '60', 'consumer':
'projects/576121055363', 'quota_limit': 'WriteRequestsPerMinutePerUser',
'quota_location': 'global', 'quota_metric': 'sheets.googleapis.com/write_requests'}},
{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Request
a higher quota limit.', 'url': 'https://cloud.google.com/docs/quota#requesting_higher_quota'}]}]}
```

I note that the quota that maxed out is Write requests on Google Sheets, and the quota seems set at 60/min. In my dashboard it says 300 curiously enough. When I tried to multiply it by 10 I got this message:
```
Hello Jérémie,

Thank you for contacting Google API Quota Support. My name is Kay and I will be assisting you with this case. This message is to confirm that we have received your request for project roseingrave-scarlatti-argos with the following values:

=== Quota Requested ===

Resource: WriteRequestsPerMinutePerProject
External Resource Name (Customer facing): Write requests per minute
Metric Name: [sheets.googleapis.com/write_requests](http://sheets.googleapis.com/write_requests)
Unit: 1/min/{project}
Dimensions: N/A
Current Quota: 300
Desired Quota: 3000
Region: GLOBAL

Upon evaluation, we are unable to grant your request at this time due to insufficient usage history on the requested resource.

What we can recommend would be for you to utilize your current quota first and submit a new request once you've hit at least 80% of your current quota for this resource.

As an additional information, the API provides batch APIs which allows for reading or updating multiple ranges of a spreadsheet in a single API request to use less quota. If the application is taking advantage of these batch APIs, please refer to our public documentation [1] for more information.

We also recommend to try to implement exponential backoff, since Exponential backoff [2] can be used to retry requests after a delay when the application encounters an error.

We truly hope this information is helpful. Should you have questions or clarifications regarding this case, please feel free to respond to this email.

Sincerely,

Kay
Google Cloud Platform Support

[1] https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/batchUpdate
[2] https://developers.google.com/drive/api/v3/handle-errors#implementing_exponential_backoff
ref:_00D00VNwG._5005w21JDnA:ref
```
Maybe it would be a good idea to do some sort of exponential backoff (when getting this specific error, wait, and try again, and wait, and try again, etc. using an exponential random time to determine how long to wait).

That means, you first wait 15 seconds. If it fails you multiple by 2, and wait 30 seconds. If it fails, you multiple by 2, wait 60 seconds, try again. If it fails, you multiply by 2, wait 120 seconds, try again, etc.

Here the exponential factor is 2, but it could be anything. Sometimes, some "jitter" is added, a random additive parameter for randomness.

Their doc might be useful.

**Comment by jlumbroso** [comment]
Actually this issue needs to be solved in the `gspread` package:
https://github.com/burnash/gspread/pull/1075

**Comment by jlumbroso** [comment]
This is resolved by the pull request I just made:
https://github.com/josephlou5/roseingrave/pull/10
